# Inserts a blank line between shell prompts
add_newline = false

[directory]
truncation_length = 100
format = "[\\[$path\\]]($style) "

[python]
version_format = 'v${major}.${minor}'

[gcloud]
disabled = true

[hostname]
ssh_only = false
format = "[$hostname]($style) "

