# Inserts a blank line between shell prompts
add_newline = false
right_format = """$time"""

[directory]
truncation_length = 100
format = "[\\[$path\\]]($style) "
home_symbol = "~"
truncate_to_repo = false

[python]
version_format = 'v${major}.${minor}'

[gcloud]
disabled = true

[hostname]
ssh_only = false
format = "[$hostname]($style) "

[c]
format = "[$symbol]($style) "

[time]
disabled = false
